import { APP_NAME } from "@/lib/app";
import { cn } from "@/lib/utils";

/** The round app mark (same drawing as the app icon) followed by the name. */
export function Wordmark({ className }: { className?: string }) {
  return (
    <span className={cn("inline-flex items-center gap-2.5", className)}>
      {/* eslint-disable-next-line @next/next/no-img-element -- tiny static image, generated by npm run icons */}
      <img src="/brand-mark.png" srcSet="/brand-mark.png 1x, /brand-mark@4x.png 4x" alt="" width={32} height={32} className="size-8" />
      <span className="text-title font-extrabold">{APP_NAME}</span>
    </span>
  );
}
